Apps/Usuario/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from . import views
from django.urls import path
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from Apps.Usuario.views import guardarLista, crud, IndexView2, IndexView , Login, ClienteCreate , home
#Login requerido
from django.contrib.auth.decorators import login_required
app_name = 'Usuario'
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'user', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)

urlpatterns = [
    #Vista del usuario sin registrar
    url(r'^$', views.home, name='home'),
    url(r'^registrar', views.ClienteCreate.as_view(), name = 'registroUsuario' ),
    url(r'^ingresar', Login.as_view(), name='login'),
    #Vista principal del mantenedor
    url(r'^mantenedor/$', login_required(IndexView), name='mantenedor'),
    #
    url(r'^guardar_lista/$', guardarLista, name='guardar_lista'),
    url(r'^producto/(?P<pk>\d+)/', IndexView2, name='productoconid'),
    #Mantenedor de listas
    url(r'^actualizarProducto/$', crud.actualizarProducto, name='actualizar_producto'),
    url(r'^([0-9]+)/editar_producto/$', crud.editarProducto, name='editar_producto'),
    url(r'^guardar_producto/(?P<pk>\d+)/', crud.guardarProducto, name='guardar_producto'),
    url(r'^guardar_tienda/$', views.guardarTienda, name='guardar_tienda'),
    url(r'^tienda/', login_required(views.IndexView3) , name='tienda'),
    url(r'^eliminartienda/(?P<pk>\d+)/', views.eliminartienda , name='eliminartienda'),
    url(r'^eliminarproducto/(?P<pk>\d+)/', views.eliminarproducto , name='eliminarproducto'),
    url(r'^actualizar_mascota/$', views.crud.actualizarProducto, name='actualizarProducto'),
    url(r'^verificartienda/(?P<pk>\d+)/', views.verificartienda , name='verificartienda'),
    #vista menu de opciones
    url(r'^menuinicio', login_required(views.menu), name='menu'),
    #vista para deslogearse
    url(r'^salir$', views.salir ,name='salir'),
    url(r'^contact$', views.contact ,name='contactanos'),
    #url para apí
    path('misfinanzasApi/', include(router.urls)),
]

ProyectoFinal/urls.py
from django.contrib import admin
from django.urls import path , include
from Apps.Usuario import urls
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'',include('Apps.Usuario.urls')),
    url(r'^accounts/', include('allauth.urls')),
    path('', include('pwa.urls')),
]

Apps/Usuario/models.py
from django.db import models
#Modelo usuario de Django
from django.contrib.auth.models import User

#Modelo de Usuarios
class Usuarios(models.Model):
    nombre = models.CharField(max_length= 50)
    apellido = models.CharField(max_length = 50)
    email = models.CharField(max_length = 30, null = True, blank = True)    
    clave = models.CharField(max_length = 30, null = True, blank = True)

#Modelo de Productos
class Lista(models.Model):
    nombrelista = models.CharField(max_length=200, blank='false')
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombrelista

class Tienda(models.Model):
    nombretienda = models.CharField(max_length=200, blank='false',unique=True)
    nombresucursal = models.CharField(max_length=200, blank='true')
    esOnline = models.BooleanField()
    direccion = models.CharField(max_length=200, blank='true')
    ciudad = models.CharField(max_length=200, blank='true')
    region = models.CharField(max_length=200, blank='true')
    verificado = models.BooleanField(default=False)
    
    def __str__(self):
        return self.nombretienda

class Producto(models.Model):
    nombreproducto = models.CharField(max_length=200, blank='true')
    costoP =  models.IntegerField()
    costoR = models.IntegerField()
    tienda = models.ForeignKey(Tienda, null=True ,on_delete=models.SET_NULL)
    lista = models.ForeignKey(Lista, null=True ,on_delete=models.SET_NULL, related_name="relatedlistas")
    notas = models.CharField(max_length=200, blank='true')
    comprado = models.BooleanField(default=False)

    def __str__(self):
        return self.nombreproducto

Apps/Usuario/forms.py
from django import forms
from .models import Usuarios, Lista
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User

#Importando para formulario de mantenedor

class ClienteForm(UserCreationForm):

    class Meta:
        model = User
        
        fields = [
            'first_name',
            'last_name',
            'email',
            'password1',
            
            
        ]

        labels = {
            
            'first_name': 'Nombre',
            'last_name': 'Apellidos',
            'email': 'Email',
            'password1':'Ingrese Clave',
            
        }

        widgets = {
            
    		'first_name': forms.TextInput(attrs={'class':'form-control'}),
            'last_name': forms.TextInput(attrs={'class':'form-control'}),
    		'email': forms.TextInput(attrs={'class':'form-control'}),
    		'password1': forms.PasswordInput(attrs={'class':'form-control'}),
            
            
        }

class FormularioLogin(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(FormularioLogin, self).__init__(*args, **kwargs)        
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['username'].widget.attrs['placeholder'] = 'Ingrese Nombre'       
        self.fields['password'].widget.attrs['class'] = 'form-control'
        self.fields['password'].widget.attrs['placeholder'] = 'Ingrese Clave'

#Formulario para Mantenedor 

class ListaForm(forms.ModelForm):
    nombrelista = forms.CharField(required=True, label='Nombre de la lista')
    class Meta:
        model = Lista
        fields = ('nombrelista',)

Apps/Usuario/views.py
from django.views.generic import CreateView, ListView, FormView
from .forms import  FormularioLogin , ClienteForm
from .models import *
from django.shortcuts import get_object_or_404, render, redirect, render, reverse
from .forms import ListaForm
from django.http import HttpResponseRedirect, HttpResponse
from django.db.models import Avg, Count, Min, Sum
from django.urls import reverse_lazy
from django.contrib.auth.models import User, Group
from django.contrib.auth import authenticate, login, logout
#from viewsets
from rest_framework import viewsets
from Apps.Usuario.serializers import UserSerializers, GroupSerializers

#Contactanos
def contact(request):
    return render(request, 'contact.html')

#Vistas para Usuario
def home(request):
    return render(request, 'home.html')

def inde(request):
    return render(request, 'login.html')

#Cerrar sesion
def salir(request):
    logout(request)
    return render(request, 'home.html', {})

class Login(FormView):
    template_name = 'login.html'
    form_class = FormularioLogin
    success_url = ('mantenedor')
 
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(self.get_success_url())
        
        else:
            return super(Login, self).dispatch(request, *args, **kwargs)
 
    def form_valid(self, form):
        login(self.request, form.get_user())
        return super(Login, self).form_valid(form)

class ClienteCreate(CreateView):
    model = User
    form_class = ClienteForm
    template_name = 'formulario.html'
    success_url = reverse_lazy('home')  

# Create your views here.
def IndexView(request):
	listas = Lista.objects.filter(user_id=request.user.id)
	result = []
	for e in listas:
		 result.append(Producto.objects.filter(lista_id=e.pk))
	num = 0
	num2 = 0
	resultadosumacostoP = 0
	resultadosumacostoR = 0
	sumaP = []
	sumaR = []
	prodC = []
	counter = 0
	for i in range(len(result)):
		for u in range(len(result[num])):
			resultadosumacostoP = resultadosumacostoP + result[num][num2].costoP
			resultadosumacostoR = resultadosumacostoR + result[num][num2].costoR
			if result[num][num2].comprado == True:
				counter = counter + 1
			num2 = num2 + 1	
		sumaP.append(resultadosumacostoP)
		sumaR.append(resultadosumacostoR)
		prodC.append(counter)	
		num = num + 1
		num2 = 0
		counter = 0
		resultadosumacostoP = 0
		resultadosumacostoR = 0	
	num = 0


	#el total de productos agregados (Listo)
	#el total de productos ya comprados (Listo)
	#el costo total presupuestado (Listo)
	#el costo total real de los productos comprados (Listo)
	return render(request,'mantenedor.html', {'Lista': listas,'listproduct': result, 'sumaP':sumaP,'sumaR':sumaR, 'counter':prodC})
	
def IndexView2(request, pk):
	producto = Producto.objects.filter(lista_id=pk)
	tiendas = Tienda.objects.all()
	tiendasf = Tienda.objects.filter(verificado=True)
	return render(request,'mantenedorproducto.html', {'producto': producto, 'lista_pk': pk, 'tiendas':tiendas, 'tiendasf':tiendasf})

def IndexView3(request):
	tiendas = Tienda.objects.all()
	tiendasf = Tienda.objects.filter(verificado=True)
	return render(request,'mantenedortienda.html', {'tiendas':tiendas,'tiendasf':tiendasf})

class crud():
	def guardarProducto(request, pk):
		if 'comprado' in request.POST:
			Validador = True
		else:
			Validador = False
		sv = Producto(
		nombreproducto=request.POST['nombreproducto'], 
		costoP=request.POST['costoP'],
		costoR=request.POST['costoR'],
		tienda = Tienda.objects.get(nombretienda=request.POST['tienda']),
		lista= Lista.objects.get(id=pk),
		notas=request.POST['notas'],
		comprado = Validador, )

		sv.save()
		return HttpResponseRedirect(reverse('Usuario:productoconid', args=[pk]))

	def editarProducto(request, data_id):
		data = get_object_or_404(Producto, pk=data_id)
		alldata = Producto.objects.order_by('nombreproducto') 
		return render(request, 'mantenedorproducto.html', {'data': data, 'qid' : data_id, 'getdata' : alldata})
	
	def actualizarProducto(request):
		ed = Producto.objects.get(pk=request.POST['qid'])

		ed.nombreproducto=request.POST['nombreproducto']
		ed.costoP=request.POST['costoP']
		ed.costoR=request.POST['costoR']
		ed.notas=request.POST['notas']
		
		ed.save()

		return HttpResponseRedirect(reverse('Usuario:productoconid', args=[ed.lista.pk]))

def guardarLista(request):
	form = ListaForm(request.POST)
	if form.is_valid():
		asd = form.save(commit=False)
		user = User.objects.get(pk=request.user.id)
		asd.user = user
		asd.save()
		form = ListaForm()
		return redirect('Usuario:mantenedor')
	return render(request, 'guardarLista.html',{'form':form})

def guardarTienda(request):
		if 'esOnline' in request.POST:
			Validador = True
		else:
			Validador = False

		tie = Tienda(
		nombretienda=request.POST['nombretienda'], 
		nombresucursal=request.POST['nombresucursal'],
		esOnline= Validador,
		direccion = request.POST['direccion'],
		ciudad = request.POST['ciudad'],
		region = request.POST['region'])
		
		tie.save()
		return HttpResponseRedirect(reverse('Usuario:tienda'))

def eliminartienda(request, pk):
		dl = Tienda.objects.get(id=pk)
		dl.delete()
		return HttpResponseRedirect(reverse('Usuario:tienda'))

def verificartienda(request, pk):
		dl = Tienda.objects.get(id=pk)
		dl.verificado = True
		dl	.save()
		return HttpResponseRedirect(reverse('Usuario:tienda'))

#vistas para menu
def menu(request):
    return render(request, 'menu.html')
        
def eliminarproducto(request, pk):
		dl = Producto.objects.get(id=pk)
		dl.delete()
		return HttpResponseRedirect(reverse('Usuario:productoconid', args=[dl.lista.pk]))


#Vista para los serializers
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all().order_by('-date_joined')
    serializer_class = UserSerializers


class GroupViewSet(viewsets.ModelViewSet):
    queryset = Group.objects.all()
    serializer_class = GroupSerializers

Apps/Usuario/templates/guardarLista.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <!--Estilos-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" >
    <link  rel="stylesheet" href="{% static 'css/modern-business.css' %}">
	<link rel="stylesheet" media="screen" href="{% static 'css/style.css' %}"> 
</head>
<body>
    <!--Navegador-->
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
            <div class="container">
              <a class="navbar-brand" href="{% url 'Usuario:menu' %}">Mis Finanzas</a>
              <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                   <li class="nav-item">
                    <a class="nav-link" href="{% url 'Usuario:salir' %}">Cerrar Sesion</a>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
        <!--campo-->
    <form method="post">
            {% csrf_token %}            
                {{ form.as_p }}
            <button type="submit"> Guardar Lista </button>
    </form>     
</body>
</html>

Apps/Usuario/templates/mantenedorproducto.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" >
    <link  rel="stylesheet" href="{% static 'css/modern-business.css' %}">
    <title>Mantenedor</title>
</head>
<body>
<!--Navegador-->
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
          <a class="navbar-brand" href="{% url 'Usuario:menu' %}">Mis Finanzas</a>
          <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
               <li class="nav-item">
                <a class="nav-link" href="{% url 'Usuario:salir' %}">Cerrar Sesion</a>
              </li>
            </ul>
          </div>
        </div>
</nav>
<!--Contenedor-->
<div class="container"> 
    <br><br>
    <div class="row">        
        <div class="col-md-4 col-sm-4 col-xs-4">
                <div class="panel panel-default">
                     <div class="panel-heading">Formulario de Producto</div>
                     <div class="panel-body">
                         <br>
                    {% if qid %}     
                    <form method="POST" action="{% url 'Usuario:actualizar_producto' %}" enctype="multipart/form-data" accept-charset="UTF-8" class="test-form">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="email">Nombre Producto</label>
                            <input required="required" class="form-control" placeholder="Nombre Producto" name="nombreproducto" type="text" value="{{ data.nombreproducto }}">
                        </div>
                        <div class="form-group">
                            <label for="username">Costo Presupuestado</label>    
                            <input type="hidden" name="qid" value="{{ data.pk }}">
                            <input required="required" class="form-control" value="{{ data.costoP }}" placeholder="Costo Presupuestado" name="costoP" type="text">
                            
                        </div>
                        <div class="form-group">
                            <label for="username">Costo Real</label>    
                            <input type="hidden" name="qid" value="{{ data.pk }}">
                            <input required="required" class="form-control" value="{{ data.costoR }}" placeholder="Costo Real" name="costoR" type="text">
                            
                        </div>
                        <div class="form-group">
                            <label for="username">Comentario</label>    
                            <input type="hidden" name="qid" value="{{ data.pk }}">
                            <input required="required" class="form-control" value="{{ data.notas }}" placeholder="Comentario" name="notas" type="text">                            
                        </div>
                        <div class="form-group">
                            <input class="btn btn-primary" type="submit" value="Actualizar Datos">
                        </div>  
                    </form>
                    {% else %}
                    <form method="POST" action="{% url 'Usuario:guardar_producto' lista_pk %}" enctype="multipart/form-data" accept-charset="UTF-8" class="test-form">
                        {% csrf_token %}
                        <div class="form-group">
                            <input required="required" class="form-control" placeholder="Nombre Producto" name="nombreproducto" type="text" value="">
                        </div>
                        <div class="form-group">  
                            <input required="required" class="form-control" value="" placeholder="Costo Presupuestado" name="costoP" type="text">     
                        </div>
                        <div class="form-group">
                            <input required="required" class="form-control" value="" placeholder="Costo Real" name="costoR" type="text">                            
                        </div>

                        <div class="form-group">
                            <select name="tienda" id="">
                                <option value="">-- Seleccione una tienda --</option>
                                {% for tie in tiendasf %}
                                <option value="{{ tie }}" name="tienda"> {{ tie }}</option>
                                {% endfor %}
                            </select>
                        </div>       

                        <div class="form-group">
                                <input required="required" class="form-control" value="" placeholder="Comentario" name="notas" type="text">                            
                        </div>                
                        <div class="form-group">  
                            <p style="text-align: center">¿Comprado? <input class="form-control" name="comprado" type="checkbox"></p> 
                        </div>                  
                            
                        <div class="form-group">
                            <input class="btn btn-primary" type="submit" value="Guardar">
                        </div>
                    </form>
                    
                     </div>
                 </div>
             </div>            

    <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">Productos</div>
                <br>
                <div class="panel-body">
                    <table class="table table-striped table-dark table-bordered datatable" cellspacing="0" width="100%">
                        <tbody>
                                <tr>
                                        <td>N°</td>
                                        <td>Nombre Producto</td>
                                        <td>Costo Presupuestado</td>
                                        <td>Costo Real</td>
                                        <td>Tienda</td>
                                        <td>Comentario</td>
                                        <td>¿Comprado?</td>
                                    </tr>
                                {% for question in producto %}
                                    <tr>
                                        <td>{{ question.pk }}</td>
                                        <td>{{ question.nombreproducto }}</td>
                                        <td>{{ question.costoP }}</td>
                                        <td>{{ question.costoR }}</td>
                                        <td>{{ question.tienda }}</td>
                                        <td>{{ question.notas }}</td>
                                        <td>{{ question.comprado|yesno:" Comprado,No comprado" }}</td>
                                        <td><a href="{% url 'Usuario:editar_producto' question.pk %}">Editar</a></td>
                                        <td><a href="{% url 'Usuario:eliminarproducto' question.pk %}">Eliminar</a></td>
                                    </tr>
                                {% endfor %}         
                            <!-- {% if producto %} -->
                            <!-- {% else %} -->
                                    <tr>
                                    <td colspan="5">No hay data disponible ..</td>
                                    </tr>
                            <!-- {% endif %} -->
                        </tbody>
                    </table>
                    {% endif %}
                </div>
            </div>
        </div>
       
    </div>
</div>
</body>
</html>

Apps/Usuario/templates/mantenedortienda.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Mantenedor</title>

    <!--Estilos-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" >
    <link  rel="stylesheet" href="{% static 'css/modern-business.css' %}">
	<link rel="stylesheet" media="screen" href="{% static 'css/style.css' %}"> 
</head>
<body>
<!--Navegador-->
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
          <a class="navbar-brand" href="{% url 'Usuario:menu' %}">Mis Finanzas</a>
          <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
               <li class="nav-item">
                <a class="nav-link" href="{% url 'Usuario:salir' %}">Cerrar Sesion</a>
              </li>
            </ul>
          </div>
</div>
</nav>
 <!--Tablas-->         
<div class="container"> 
    <br><br>
    <div class="row">        
        <div class="col-md-4 col-sm-4 col-xs-4">
                <div class="panel panel-default">
                     <div class="panel-heading">Formulario de Tiendas</div>
                     <div class="panel-body">
                         <br>
                    <form method="POST" action="{% url 'Usuario:guardar_tienda' %}" enctype="multipart/form-data" accept-charset="UTF-8" class="test-form">
                        {% csrf_token %}
                        <div class="form-group">
                            <input required="required" class="form-control" placeholder="Nombre Tienda" name="nombretienda" type="text" value="">
                        </div>
                        <div class="form-group">  
                            <input required="required" class="form-control" value="" placeholder="Nombre Sucursal" name="nombresucursal" type="text">     
                        </div>
                        <div class="form-group">  
                                <p style="text-align: center"> ¿Es online? <input class="form-control" name="esOnline" type="checkbox"></p> 
                            </div>            
                        <div class="form-group">
                                <input class="form-control" value="" placeholder="Dirección" name="direccion" type="text">                            
                        </div>                
                        <div class="form-group">
                                <input class="form-control" value="" placeholder="Ciudad" name="ciudad" type="text">                    
                        </div>                      
                        <div class="form-group">
                                <input class="form-control" value="" placeholder="Region" name="region" type="text">                            
                        </div>           
                        <div class="form-group">
                            <input class="btn btn-primary" type="submit" value="Guardar">
                        </div>
                    </form>
                     </div>
                 </div>
             </div>            

    <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">Tiendas</div>
                <br>
                <div class="panel-body">
                    <table class="table table-striped table-dark table-bordered datatable" cellspacing="0" width="100%">
                        <tbody> 
                                <tr>
                                        <td>N°</td>
                                        <td>Nombre Tienda</td>
                                        <td>Nombre Sucursal</td>
                                        <td>Tienda</td>
                                        <td>Direccion</td>
                                        <td>Ciudad</td>
                                        <td>Region</td>
                                    </tr>
                                    {% if request.user.is_superuser %}
                                {% for question in tiendas %}
                                    <tr>
                                        <td>{{ question.id }}</td>
                                        <td>{{ question.nombretienda }}</td>
                                        <td>{{ question.nombresucursal }}</td>
                                        <td>{{ question.esOnline }}</td>
                                        <td>{{ question.direccion }}</td>
                                        <td>{{ question.ciudad }}</td>
                                        <td>{{ question.region }}</td>                                    
                                                <td><a href="{% url 'Usuario:verificartienda' question.id %}">Verificar</a></td>
                                                <td><a onclick="return confirm('Esta seguro que quiere eliminar ?');" href="{% url 'Usuario:eliminartienda' question.id %}">Eliminar</a></td>
                                        {% endfor %}  
                                            {% else %}
                                        {% for question in tiendasf %}
                                            <tr>
                                                <td>{{ question.id }}</td>
                                                <td>{{ question.nombretienda }}</td>
                                                <td>{{ question.nombresucursal }}</td>
                                                <td>{{ question.esOnline|yesno:" Online,Fisica" }}</td>
                                                <td>{{ question.direccion }}</td>
                                                <td>{{ question.ciudad }}</td>
                                                <td>{{ question.region }}</td>
                                                {% endfor %} 
                                            {% endif %}
                                    </tr>       
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>